// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.2
// source: poll_dev.proto

package services_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PollTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PollTypeRequest) Reset() {
	*x = PollTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poll_dev_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollTypeRequest) ProtoMessage() {}

func (x *PollTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_dev_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollTypeRequest.ProtoReflect.Descriptor instead.
func (*PollTypeRequest) Descriptor() ([]byte, []int) {
	return file_poll_dev_proto_rawDescGZIP(), []int{0}
}

type PollTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *PollTypeResponse) Reset() {
	*x = PollTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poll_dev_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollTypeResponse) ProtoMessage() {}

func (x *PollTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_dev_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollTypeResponse.ProtoReflect.Descriptor instead.
func (*PollTypeResponse) Descriptor() ([]byte, []int) {
	return file_poll_dev_proto_rawDescGZIP(), []int{1}
}

func (x *PollTypeResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ChangeMetricRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Settings []*Settings `protobuf:"bytes,1,rep,name=Settings,proto3" json:"Settings,omitempty"`
	PollItem []*PollItem `protobuf:"bytes,2,rep,name=PollItem,proto3" json:"PollItem,omitempty"`
}

func (x *ChangeMetricRequest) Reset() {
	*x = ChangeMetricRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poll_dev_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMetricRequest) ProtoMessage() {}

func (x *ChangeMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_dev_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMetricRequest.ProtoReflect.Descriptor instead.
func (*ChangeMetricRequest) Descriptor() ([]byte, []int) {
	return file_poll_dev_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeMetricRequest) GetSettings() []*Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *ChangeMetricRequest) GetPollItem() []*PollItem {
	if x != nil {
		return x.PollItem
	}
	return nil
}

type ChangeMetricResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ChangeMetricResponse) Reset() {
	*x = ChangeMetricResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poll_dev_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMetricResponse) ProtoMessage() {}

func (x *ChangeMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_dev_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMetricResponse.ProtoReflect.Descriptor instead.
func (*ChangeMetricResponse) Descriptor() ([]byte, []int) {
	return file_poll_dev_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeMetricResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PollRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Settings  []*Settings `protobuf:"bytes,1,rep,name=Settings,proto3" json:"Settings,omitempty"`
	PollItems []*PollItem `protobuf:"bytes,2,rep,name=PollItems,proto3" json:"PollItems,omitempty"`
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poll_dev_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_dev_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_poll_dev_proto_rawDescGZIP(), []int{4}
}

func (x *PollRequest) GetSettings() []*Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *PollRequest) GetPollItems() []*PollItem {
	if x != nil {
		return x.PollItems
	}
	return nil
}

type PollResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   string      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PollItem []*PollItem `protobuf:"bytes,2,rep,name=PollItem,proto3" json:"PollItem,omitempty"`
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poll_dev_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_dev_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_poll_dev_proto_rawDescGZIP(), []int{5}
}

func (x *PollResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PollResponse) GetPollItem() []*PollItem {
	if x != nil {
		return x.PollItem
	}
	return nil
}

type PollItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Addr  string  `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Desc  string  `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Value *string `protobuf:"bytes,4,opt,name=value,proto3,oneof" json:"value,omitempty"`
}

func (x *PollItem) Reset() {
	*x = PollItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poll_dev_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollItem) ProtoMessage() {}

func (x *PollItem) ProtoReflect() protoreflect.Message {
	mi := &file_poll_dev_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollItem.ProtoReflect.Descriptor instead.
func (*PollItem) Descriptor() ([]byte, []int) {
	return file_poll_dev_proto_rawDescGZIP(), []int{6}
}

func (x *PollItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PollItem) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *PollItem) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *PollItem) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type Settings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Settings) Reset() {
	*x = Settings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poll_dev_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_poll_dev_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_poll_dev_proto_rawDescGZIP(), []int{7}
}

func (x *Settings) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Settings) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PresetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PresetRequest) Reset() {
	*x = PresetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poll_dev_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresetRequest) ProtoMessage() {}

func (x *PresetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_dev_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresetRequest.ProtoReflect.Descriptor instead.
func (*PresetRequest) Descriptor() ([]byte, []int) {
	return file_poll_dev_proto_rawDescGZIP(), []int{8}
}

type PresetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Preset string `protobuf:"bytes,1,opt,name=preset,proto3" json:"preset,omitempty"`
}

func (x *PresetResponse) Reset() {
	*x = PresetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poll_dev_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresetResponse) ProtoMessage() {}

func (x *PresetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_dev_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresetResponse.ProtoReflect.Descriptor instead.
func (*PresetResponse) Descriptor() ([]byte, []int) {
	return file_poll_dev_proto_rawDescGZIP(), []int{9}
}

func (x *PresetResponse) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

var File_poll_dev_proto protoreflect.FileDescriptor

var file_poll_dev_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x6f, 0x6c, 0x6c, 0x5f, 0x64, 0x65, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x50, 0x6f, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x10, 0x50, 0x6f, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x83, 0x01, 0x0a,
	0x13, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50,
	0x6f, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x52, 0x08, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x35, 0x0a, 0x08, 0x50,
	0x6f, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x6f, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x50, 0x6f, 0x6c, 0x6c, 0x49, 0x74,
	0x65, 0x6d, 0x22, 0x2e, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x7d, 0x0a, 0x0b, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x35, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x08,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x37, 0x0a, 0x09, 0x50, 0x6f, 0x6c, 0x6c,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x44, 0x72,
	0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f,
	0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x50, 0x6f, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x22, 0x5d, 0x0a, 0x0c, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x35, 0x0a, 0x08, 0x50, 0x6f, 0x6c,
	0x6c, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x44, 0x72,
	0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f,
	0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x50, 0x6f, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d,
	0x22, 0x6b, 0x0a, 0x08, 0x50, 0x6f, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x19, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x34, 0x0a,
	0x08, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x28, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x73, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x73, 0x65, 0x74, 0x32, 0xd1,
	0x02, 0x0a, 0x11, 0x50, 0x6f, 0x6c, 0x6c, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x08, 0x50, 0x6f, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x20, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x04, 0x50, 0x6f, 0x6c, 0x6c, 0x12, 0x1c, 0x2e,
	0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x44, 0x72,
	0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x0c, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x24, 0x2e, 0x44, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x06, 0x50, 0x72, 0x65, 0x73, 0x65,
	0x74, 0x12, 0x1e, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_poll_dev_proto_rawDescOnce sync.Once
	file_poll_dev_proto_rawDescData = file_poll_dev_proto_rawDesc
)

func file_poll_dev_proto_rawDescGZIP() []byte {
	file_poll_dev_proto_rawDescOnce.Do(func() {
		file_poll_dev_proto_rawDescData = protoimpl.X.CompressGZIP(file_poll_dev_proto_rawDescData)
	})
	return file_poll_dev_proto_rawDescData
}

var file_poll_dev_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_poll_dev_proto_goTypes = []interface{}{
	(*PollTypeRequest)(nil),      // 0: DriverPollProto.PollTypeRequest
	(*PollTypeResponse)(nil),     // 1: DriverPollProto.PollTypeResponse
	(*ChangeMetricRequest)(nil),  // 2: DriverPollProto.ChangeMetricRequest
	(*ChangeMetricResponse)(nil), // 3: DriverPollProto.ChangeMetricResponse
	(*PollRequest)(nil),          // 4: DriverPollProto.PollRequest
	(*PollResponse)(nil),         // 5: DriverPollProto.PollResponse
	(*PollItem)(nil),             // 6: DriverPollProto.PollItem
	(*Settings)(nil),             // 7: DriverPollProto.Settings
	(*PresetRequest)(nil),        // 8: DriverPollProto.PresetRequest
	(*PresetResponse)(nil),       // 9: DriverPollProto.PresetResponse
}
var file_poll_dev_proto_depIdxs = []int32{
	7, // 0: DriverPollProto.ChangeMetricRequest.Settings:type_name -> DriverPollProto.Settings
	6, // 1: DriverPollProto.ChangeMetricRequest.PollItem:type_name -> DriverPollProto.PollItem
	7, // 2: DriverPollProto.PollRequest.Settings:type_name -> DriverPollProto.Settings
	6, // 3: DriverPollProto.PollRequest.PollItems:type_name -> DriverPollProto.PollItem
	6, // 4: DriverPollProto.PollResponse.PollItem:type_name -> DriverPollProto.PollItem
	0, // 5: DriverPollProto.PollDriverService.PollType:input_type -> DriverPollProto.PollTypeRequest
	4, // 6: DriverPollProto.PollDriverService.Poll:input_type -> DriverPollProto.PollRequest
	2, // 7: DriverPollProto.PollDriverService.ChangeMetric:input_type -> DriverPollProto.ChangeMetricRequest
	8, // 8: DriverPollProto.PollDriverService.Preset:input_type -> DriverPollProto.PresetRequest
	1, // 9: DriverPollProto.PollDriverService.PollType:output_type -> DriverPollProto.PollTypeResponse
	5, // 10: DriverPollProto.PollDriverService.Poll:output_type -> DriverPollProto.PollResponse
	3, // 11: DriverPollProto.PollDriverService.ChangeMetric:output_type -> DriverPollProto.ChangeMetricResponse
	9, // 12: DriverPollProto.PollDriverService.Preset:output_type -> DriverPollProto.PresetResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_poll_dev_proto_init() }
func file_poll_dev_proto_init() {
	if File_poll_dev_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_poll_dev_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poll_dev_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poll_dev_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeMetricRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poll_dev_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeMetricResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poll_dev_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poll_dev_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poll_dev_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poll_dev_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Settings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poll_dev_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poll_dev_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_poll_dev_proto_msgTypes[6].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_poll_dev_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poll_dev_proto_goTypes,
		DependencyIndexes: file_poll_dev_proto_depIdxs,
		MessageInfos:      file_poll_dev_proto_msgTypes,
	}.Build()
	File_poll_dev_proto = out.File
	file_poll_dev_proto_rawDesc = nil
	file_poll_dev_proto_goTypes = nil
	file_poll_dev_proto_depIdxs = nil
}
