// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.2
// source: poll_dev.proto

package services_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PollRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Settings []*Settings `protobuf:"bytes,1,rep,name=Settings,proto3" json:"Settings,omitempty"`
	PollItem []*PollItem `protobuf:"bytes,2,rep,name=PollItem,proto3" json:"PollItem,omitempty"`
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poll_dev_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_dev_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_poll_dev_proto_rawDescGZIP(), []int{0}
}

func (x *PollRequest) GetSettings() []*Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *PollRequest) GetPollItem() []*PollItem {
	if x != nil {
		return x.PollItem
	}
	return nil
}

type PollResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PollValue []*PollValue `protobuf:"bytes,1,rep,name=PollValue,proto3" json:"PollValue,omitempty"`
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poll_dev_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_dev_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_poll_dev_proto_rawDescGZIP(), []int{1}
}

func (x *PollResponse) GetPollValue() []*PollValue {
	if x != nil {
		return x.PollValue
	}
	return nil
}

type ChangeMetricRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Settings *Settings  `protobuf:"bytes,1,opt,name=Settings,proto3" json:"Settings,omitempty"`
	Metric   *PollValue `protobuf:"bytes,2,opt,name=Metric,proto3" json:"Metric,omitempty"`
}

func (x *ChangeMetricRequest) Reset() {
	*x = ChangeMetricRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poll_dev_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMetricRequest) ProtoMessage() {}

func (x *ChangeMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_dev_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMetricRequest.ProtoReflect.Descriptor instead.
func (*ChangeMetricRequest) Descriptor() ([]byte, []int) {
	return file_poll_dev_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeMetricRequest) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *ChangeMetricRequest) GetMetric() *PollValue {
	if x != nil {
		return x.Metric
	}
	return nil
}

type ChangeMetricResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ChangeMetricResponse) Reset() {
	*x = ChangeMetricResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poll_dev_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMetricResponse) ProtoMessage() {}

func (x *ChangeMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_dev_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMetricResponse.ProtoReflect.Descriptor instead.
func (*ChangeMetricResponse) Descriptor() ([]byte, []int) {
	return file_poll_dev_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeMetricResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PresetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PresetRequest) Reset() {
	*x = PresetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poll_dev_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresetRequest) ProtoMessage() {}

func (x *PresetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_dev_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresetRequest.ProtoReflect.Descriptor instead.
func (*PresetRequest) Descriptor() ([]byte, []int) {
	return file_poll_dev_proto_rawDescGZIP(), []int{4}
}

type PresetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Preset string `protobuf:"bytes,1,opt,name=preset,proto3" json:"preset,omitempty"`
}

func (x *PresetResponse) Reset() {
	*x = PresetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poll_dev_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresetResponse) ProtoMessage() {}

func (x *PresetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_dev_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresetResponse.ProtoReflect.Descriptor instead.
func (*PresetResponse) Descriptor() ([]byte, []int) {
	return file_poll_dev_proto_rawDescGZIP(), []int{5}
}

func (x *PresetResponse) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

type PollItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PollItem) Reset() {
	*x = PollItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poll_dev_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollItem) ProtoMessage() {}

func (x *PollItem) ProtoReflect() protoreflect.Message {
	mi := &file_poll_dev_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollItem.ProtoReflect.Descriptor instead.
func (*PollItem) Descriptor() ([]byte, []int) {
	return file_poll_dev_proto_rawDescGZIP(), []int{6}
}

func (x *PollItem) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *PollItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PollValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr  string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PollValue) Reset() {
	*x = PollValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poll_dev_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollValue) ProtoMessage() {}

func (x *PollValue) ProtoReflect() protoreflect.Message {
	mi := &file_poll_dev_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollValue.ProtoReflect.Descriptor instead.
func (*PollValue) Descriptor() ([]byte, []int) {
	return file_poll_dev_proto_rawDescGZIP(), []int{7}
}

func (x *PollValue) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *PollValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PollValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Settings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Settings) Reset() {
	*x = Settings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poll_dev_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_poll_dev_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_poll_dev_proto_rawDescGZIP(), []int{8}
}

func (x *Settings) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Settings) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_poll_dev_proto protoreflect.FileDescriptor

var file_poll_dev_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x6f, 0x6c, 0x6c, 0x5f, 0x64, 0x65, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x7b, 0x0a, 0x0b, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x35, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x08, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x35, 0x0a, 0x08, 0x50, 0x6f, 0x6c, 0x6c, 0x49,
	0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x44, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x6c, 0x6c,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x50, 0x6f, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x48,
	0x0a, 0x0c, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38,
	0x0a, 0x09, 0x50, 0x6f, 0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x50,
	0x6f, 0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x80, 0x01, 0x0a, 0x13, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x35, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x08, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x32, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72,
	0x50, 0x6f, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x06, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x22, 0x2e, 0x0a, 0x14, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x50,
	0x72, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x28, 0x0a, 0x0e,
	0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x72, 0x65, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x72, 0x65, 0x73, 0x65, 0x74, 0x22, 0x32, 0x0a, 0x08, 0x50, 0x6f, 0x6c, 0x6c, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x49, 0x0a, 0x09, 0x50, 0x6f,
	0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x34, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xf9, 0x01, 0x0a, 0x0a,
	0x50, 0x6f, 0x6c, 0x6c, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x04, 0x50, 0x6f,
	0x6c, 0x6c, 0x12, 0x1c, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x5b, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12,
	0x24, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6f,
	0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x06,
	0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x12, 0x1e, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50,
	0x6f, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x50,
	0x6f, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_poll_dev_proto_rawDescOnce sync.Once
	file_poll_dev_proto_rawDescData = file_poll_dev_proto_rawDesc
)

func file_poll_dev_proto_rawDescGZIP() []byte {
	file_poll_dev_proto_rawDescOnce.Do(func() {
		file_poll_dev_proto_rawDescData = protoimpl.X.CompressGZIP(file_poll_dev_proto_rawDescData)
	})
	return file_poll_dev_proto_rawDescData
}

var file_poll_dev_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_poll_dev_proto_goTypes = []interface{}{
	(*PollRequest)(nil),          // 0: DriverPollProto.PollRequest
	(*PollResponse)(nil),         // 1: DriverPollProto.PollResponse
	(*ChangeMetricRequest)(nil),  // 2: DriverPollProto.ChangeMetricRequest
	(*ChangeMetricResponse)(nil), // 3: DriverPollProto.ChangeMetricResponse
	(*PresetRequest)(nil),        // 4: DriverPollProto.PresetRequest
	(*PresetResponse)(nil),       // 5: DriverPollProto.PresetResponse
	(*PollItem)(nil),             // 6: DriverPollProto.PollItem
	(*PollValue)(nil),            // 7: DriverPollProto.PollValue
	(*Settings)(nil),             // 8: DriverPollProto.Settings
}
var file_poll_dev_proto_depIdxs = []int32{
	8, // 0: DriverPollProto.PollRequest.Settings:type_name -> DriverPollProto.Settings
	6, // 1: DriverPollProto.PollRequest.PollItem:type_name -> DriverPollProto.PollItem
	7, // 2: DriverPollProto.PollResponse.PollValue:type_name -> DriverPollProto.PollValue
	8, // 3: DriverPollProto.ChangeMetricRequest.Settings:type_name -> DriverPollProto.Settings
	7, // 4: DriverPollProto.ChangeMetricRequest.Metric:type_name -> DriverPollProto.PollValue
	0, // 5: DriverPollProto.PollDriver.Poll:input_type -> DriverPollProto.PollRequest
	2, // 6: DriverPollProto.PollDriver.ChangeMetric:input_type -> DriverPollProto.ChangeMetricRequest
	4, // 7: DriverPollProto.PollDriver.Preset:input_type -> DriverPollProto.PresetRequest
	1, // 8: DriverPollProto.PollDriver.Poll:output_type -> DriverPollProto.PollResponse
	3, // 9: DriverPollProto.PollDriver.ChangeMetric:output_type -> DriverPollProto.ChangeMetricResponse
	5, // 10: DriverPollProto.PollDriver.Preset:output_type -> DriverPollProto.PresetResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_poll_dev_proto_init() }
func file_poll_dev_proto_init() {
	if File_poll_dev_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_poll_dev_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poll_dev_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poll_dev_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeMetricRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poll_dev_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeMetricResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poll_dev_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poll_dev_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poll_dev_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poll_dev_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poll_dev_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Settings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_poll_dev_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poll_dev_proto_goTypes,
		DependencyIndexes: file_poll_dev_proto_depIdxs,
		MessageInfos:      file_poll_dev_proto_msgTypes,
	}.Build()
	File_poll_dev_proto = out.File
	file_poll_dev_proto_rawDesc = nil
	file_poll_dev_proto_goTypes = nil
	file_poll_dev_proto_depIdxs = nil
}
