// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.2
// source: poll_dev.proto

package services_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PollDriverClient is the client API for PollDriver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PollDriverClient interface {
	Poll(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*PollResponse, error)
	ChangeMetric(ctx context.Context, in *ChangeMetricRequest, opts ...grpc.CallOption) (*ChangeMetricResponse, error)
	Preset(ctx context.Context, in *PresetRequest, opts ...grpc.CallOption) (*PresetResponse, error)
}

type pollDriverClient struct {
	cc grpc.ClientConnInterface
}

func NewPollDriverClient(cc grpc.ClientConnInterface) PollDriverClient {
	return &pollDriverClient{cc}
}

func (c *pollDriverClient) Poll(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*PollResponse, error) {
	out := new(PollResponse)
	err := c.cc.Invoke(ctx, "/DriverPollProto.PollDriver/Poll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollDriverClient) ChangeMetric(ctx context.Context, in *ChangeMetricRequest, opts ...grpc.CallOption) (*ChangeMetricResponse, error) {
	out := new(ChangeMetricResponse)
	err := c.cc.Invoke(ctx, "/DriverPollProto.PollDriver/ChangeMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollDriverClient) Preset(ctx context.Context, in *PresetRequest, opts ...grpc.CallOption) (*PresetResponse, error) {
	out := new(PresetResponse)
	err := c.cc.Invoke(ctx, "/DriverPollProto.PollDriver/Preset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PollDriverServer is the server API for PollDriver service.
// All implementations must embed UnimplementedPollDriverServer
// for forward compatibility
type PollDriverServer interface {
	Poll(context.Context, *PollRequest) (*PollResponse, error)
	ChangeMetric(context.Context, *ChangeMetricRequest) (*ChangeMetricResponse, error)
	Preset(context.Context, *PresetRequest) (*PresetResponse, error)
	mustEmbedUnimplementedPollDriverServer()
}

// UnimplementedPollDriverServer must be embedded to have forward compatible implementations.
type UnimplementedPollDriverServer struct {
}

func (UnimplementedPollDriverServer) Poll(context.Context, *PollRequest) (*PollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Poll not implemented")
}
func (UnimplementedPollDriverServer) ChangeMetric(context.Context, *ChangeMetricRequest) (*ChangeMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeMetric not implemented")
}
func (UnimplementedPollDriverServer) Preset(context.Context, *PresetRequest) (*PresetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Preset not implemented")
}
func (UnimplementedPollDriverServer) mustEmbedUnimplementedPollDriverServer() {}

// UnsafePollDriverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PollDriverServer will
// result in compilation errors.
type UnsafePollDriverServer interface {
	mustEmbedUnimplementedPollDriverServer()
}

func RegisterPollDriverServer(s grpc.ServiceRegistrar, srv PollDriverServer) {
	s.RegisterService(&PollDriver_ServiceDesc, srv)
}

func _PollDriver_Poll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollDriverServer).Poll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DriverPollProto.PollDriver/Poll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollDriverServer).Poll(ctx, req.(*PollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollDriver_ChangeMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollDriverServer).ChangeMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DriverPollProto.PollDriver/ChangeMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollDriverServer).ChangeMetric(ctx, req.(*ChangeMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollDriver_Preset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PresetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollDriverServer).Preset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DriverPollProto.PollDriver/Preset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollDriverServer).Preset(ctx, req.(*PresetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PollDriver_ServiceDesc is the grpc.ServiceDesc for PollDriver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PollDriver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DriverPollProto.PollDriver",
	HandlerType: (*PollDriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Poll",
			Handler:    _PollDriver_Poll_Handler,
		},
		{
			MethodName: "ChangeMetric",
			Handler:    _PollDriver_ChangeMetric_Handler,
		},
		{
			MethodName: "Preset",
			Handler:    _PollDriver_Preset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "poll_dev.proto",
}
